aws_region              = "us-east-1"
app_name                = "provision-demo"
environment             = "production"
cognito_domain_prefix   = "provision-demo"
platform_repo_full_name = "duality72/provision-demo-platform"
age_public_key          = "age1u7f0v2g3xttxeuxw0nfa8q0lgzwztglz77vcscefd78a2nff0dzsr7z9z7"
