aws_region              = "us-east-1"
app_name                = "provision-demo"
environment             = "production"
cognito_domain_prefix   = "provision-demo"
platform_repo_full_name = "duality72/provision-demo-platform"
